<?php

namespace CryptoExchanges\Binance\Spot;

use CryptoExchanges\Core\ExchangeApiRouteInterface;

class BinanceSpotApiRoutes implements ExchangeApiRouteInterface 
{
    public function getRoutes()
    {
        return [
            'system_status' => [
                'route' => '/sapi/v1/system/status',
                'method' => 'GET',
                'apiKey' => false,
            ],
            'account_all_coin' => [
                'route' => '/sapi/v1/capital/config/getall',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'signature' => true,
                    'timestamp' => true,
                    'recvWindow' => false,
                ],
            ],
            'daily_account_snapshot ' => [
                'route' => '/sapi/v1/accountSnapshot',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'signature' => true,
                    'timestamp' => true,
                    'type' => true,
                    'startTime' => false,
                    'endTime' => false,
                    'limit' => false,
                    'recvWindow' => false,
                ],
            ],
            'disable_fast_withdraw_switch' => [
                'route' => '/sapi/v1/account/disableFastWithdrawSwitch',
                'method' => 'POST',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'recvWindow' => false,
                    'timestamp' => true,
                ]
            ],
            'enable_fast_withdraw_switch' => [
                'route' => '/sapi/v1/account/enableFastWithdrawSwitch',
                'method' => 'POST',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'recvWindow' => false,
                    'timestamp' => true,
                ]
            ],
            'withdraw' => [
                'route' => '/sapi/v1/capital/withdraw/apply',
                'method' => 'POST',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'coin' => true,
                    'withdrawOrderId' => false,
                    'network' => false,
                    'address' => true,
                    'addressTag' => false,
                    'amount' => true,
                    'transactionFeeFlag' => false,
                    'name' => false, 
                    'recvWindow' => false,
                    'timestamp' => true,
                ]
            ],
            'deposit_history' => [
                'route' => '/sapi/v1/capital/deposit/hisrec',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'coin' => false,
                    'status' => false,
                    'startTime' => false,
                    'endTime' => false,
                    'offset' => false,
                    'limit' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ]
            ],
            'withdraw_history' => [
                'route' => '/sapi/v1/capital/withdraw/history',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'coin' => false,
                    'withdrawOrderId' => false,
                    'status' => false,
                    'offset' => false,
                    'limit' => false,
                    'startTime' => false,
                    'endTime' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ]
            ],
            'deposit_address' => [
                'route' => '/sapi/v1/capital/deposit/address',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'coin' => false,
                    'network' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ]
            ],
            'account_status' => [
                'route' => '/sapi/v1/account/status',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'timestamp' => true,
                    'recvWindow' => false,
                ],
            ],
            'trading_status' => [
                'route' => '/sapi/v1/account/apiTradingStatus',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'timestamp' => true,
                    'recvWindow' => false,
                ],
            ],
            'dust_log' => [
                'route' => '/sapi/v1/asset/dribblet',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'startTime' => false,
                    'endTime' => false,
                    'timestamp' => true,
                    'recvWindow' => false,
                ],
            ],
            'dust_transfer' => [
                'route' => '/sapi/v1/asset/dust',
                'method' => 'POST',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'asset' => true,
                    'timestamp' => true,
                    'recvWindow' => false,
                ],
            ],
            'asset_dividend_record ' => [
                'route' => '/sapi/v1/asset/assetDividend',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'asset' => false,
                    'startTime' => false,
                    'endTime' => false,
                    'limit' => false,
                    'timestamp' => true,
                    'recvWindow' => false,
                ],
            ],
            'asset_detail ' => [
                'route' => '/sapi/v1/asset/assetDetail',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'asset' => false,
                    'timestamp' => true,
                    'recvWindow' => false,
                ],
            ],
            'trade_fee' => [
                'route' => '/sapi/v1/asset/tradeFee',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'timestamp' => true,
                    'recvWindow' => false,
                    'symbol' => false,
                ],
            ],
            'user_universal_transfer' => [
                'route' => '/sapi/v1/asset/transfer',
                'method' => 'POST',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'type' => true,
                    'asset' => true,
                    'amount' => true,
                    'fromSymbol' => false,
                    'toSymbol' => false,
                    'recvWindow' => false,
                    'symbol' => false,
                ],
            ],
            'query_user_universal_transfer_history' => [
                'route' => '/sapi/v1/asset/transfer',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'type' => true,
                    'startTime' => false,
                    'endTime' => false,
                    'current' => false,
                    'size' => false,
                    'fromSymbol' => false,
                    'toSymbol' => false,
                    'recvWindow' => false,
                    'symbol' => false,
                ],
            ],
            'funding_wallet' => [
                'route' => '/sapi/v1/asset/get-funding-asset',
                'method' => 'POST',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'asset' => false,
                    'needBtcValuation' => false,
                    'recvWindow' => false,
                    'symbol' => false,
                ],
            ],
            'get_api_key_permission' => [
                'route' => '/sapi/v1/account/apiRestrictions',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'recvWindow' => false,
                    'symbol' => false,
                ],
            ],
            'create_a_virtual_sub-account' => [
                'route' => '/sapi/v1/sub-account/virtualSubAccount',
                'method' => 'POST',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'subAccountString' => true,
                    'recvWindow' => false,
                    'symbol' => false,
                ],
            ],
            'query_sub-account_list' => [
                'route' => '/sapi/v1/sub-account/list',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'email' => false,
                    'isFreeze' => false,
                    'page' => false,
                    'limit' => false,
                    'recvWindow' => false,
                    'symbol' => false,
                ],
            ],
            'query_sub-account_spot_asset_transfer_history' => [
                'route' => '/sapi/v1/sub-account/sub/transfer/history',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'fromEmail' => false,
                    'toEmail' => false,
                    'startTime' => false,
                    'endTime' => false,
                    'page' => false,
                    'limit' => false,
                    'recvWindow' => false,
                    'symbol' => false,
                ],
            ],
            'query_sub-account_futures_asset_transfer_history' => [
                'route' => '/sapi/v1/sub-account/futures/internalTransfer',
                'method' => 'GET',
                'apiKey' => true,
                'signature' => true,
                'params' => [
                    'email' => true,
                    'futuresType' => true,
                    'startTime' => false,
                    'endTime' => false,
                    'page' => false,
                    'limit' => false,
                    'recvWindow' => false,
                    'symbol' => false,
                ],
            ],
            'market_ping' => [
                'route' => '/api/v3/ping',
                'method' => 'GET',
                'apiKey' => false,
            ],
            'market_time' => [
                'route' => '/api/v3/time',
                'method' => 'GET',
                'apiKey' => false,
            ],
            'exchange_info' => [
                'route' => '/api/v3/exchangeInfo',
                'method' => 'GET',
                'apiKey' => false,
            ],
            'order_book' => [
                'route' => '/api/v3/depth',
                'method' => 'GET',
                'apiKey' => false,
                'params' => [
                    'symbol' => true,
                    'limit' => false,
                ],
            ],
            'recent_trades' => [
                'route' => '/api/v3/trades',
                'method' => 'GET',
                'apiKey' => false,
                'params' => [
                    'symbol' => true,
                    'limit' => false,
                ],
            ],
            'historical_trades' => [
                'route' => '/api/v3/historicalTrades',
                'method' => 'GET',
                'apiKey' => true,
                'params' => [
                    'symbol' => true,
                    'limit' => false,
                    'fromId' => false,
                ],
            ],
            'aggregate_trades' => [
                'route' => '/api/v3/aggTrades',
                'method' => 'GET',
                'apiKey' => false,
                'params' => [
                    'symbol' => true,
                    'fromId' => false,
                    'startTime' => false,
                    'endTime' => false,
                    'limit' => false,
                ],
            ],
            'candlestick' => [
                'route' => '/api/v3/klines',
                'method' => 'GET',
                'apiKey' => false,
                'params' => [
                    'symbol' => true,
                    'interval' => true,
                    'startTime' => false,
                    'endTime' => false,
                    'limit' => false,
                ],
            ],
            'current_average_price' => [
                'route' => '/api/v3/avgPrice',
                'method' => 'GET',
                'apiKey' => false,
                'params' => [
                    'symbol' => true,
                ],
            ],
            '24h_change_static' => [
                'route' => '/api/v3/ticker/24hr',
                'method' => 'GET',
                'apiKey' => false,
                'params' => [
                    'symbol' => false,
                ],
            ],
            'current_price' => [
                'route' => '/api/v3/ticker/price',
                'method' => 'GET',
                'apiKey' => false,
                'params' => [
                    'symbol' => false,
                ],
            ],
            'first_line_order_book' => [
                'route' => '/api/v3/ticker/bookTicker',
                'method' => 'GET',
                'apiKey' => false,
                'params' => [
                    'symbol' => false,
                ],
            ],
            'open_order' => [
                'route' => '/api/v3/order',
                'method' => 'POST',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'symbol' => true,
                    'side' => true,
                    'type' => true,
                    'timeInForce' => false,
                    'quantity' => true,
                    'quoteOrderQty' => false,
                    'price' => false,
                    'newClientOrderId' => false,
                    'stopPrice' => false,
                    'icebergQty' => false,
                    'newOrderRespType' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
            'cancel_order' => [
                'route' => '/api/v3/order',
                'method' => 'DELETE',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'symbol' => true,
                    'orderId' => false,
                    'origClientOrderId' => false,
                    'newClientOrderId' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
            'get_order' => [
                'route' => '/api/v3/order',
                'method' => 'GET',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'symbol' => true,
                    'orderId' => false,
                    'origClientOrderId' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
            'cancel_all_open_orders' => [
                'route' => '/api/v3/opefalserders',
                'method' => 'DELETE',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'symbol' => true,
                    'timestamp' => true,
                    'recvWindow' => false,
                ],
            ],
            'get_all_open_orders' => [
                'route' => '/api/v3/opefalserders',
                'method' => 'GET',
                'apiKey' => true,
                'params' => [
                    'symbol' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
            'get_all_order' => [
                'route' => '/api/v3/allOrders',
                'method' => 'GET',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'symbol' => true,
                    'orderId' => false,
                    'startTime' => false,
                    'endTime' => false,
                    'limit' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
            'open_oco_order' => [
                'route' => '/api/v3/order/oco',
                'method' => 'POST',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'symbol' => true,
                    'listClientOrderId' => false,
                    'side' => true,
                    'quantity' => true,
                    'limitClientOrderId' => false,
                    'price' => true,
                    'limitIcebergQty' => false,
                    'stopClientOrderId' => false,
                    'stopPrice' => true,
                    'stopLimitPrice' => false,
                    'stopIcebergQty' => false,
                    'stopLimitTimeInForce' => false,
                    'newOrderRespType' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
            'cancel_oco_order' => [
                'route' => '/api/v3/orderList',
                'method' => 'DELETE',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'symbol' => true,
                    'orderListId' => false,
                    'listClientOrderId' => false,
                    'newClientOrderId' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
            'get_oco_order' => [
                'route' => '/api/v3/orderList',
                'method' => 'GET',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'orderListId' => false,
                    'origClientOrderId' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
            'get_all_oco_order' => [
                'route' => '/api/v3/allOrderList',
                'method' => 'GET',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'fromId' => false,
                    'startTime' => false,
                    'endTime' => false,
                    'limit' => false,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
            'get_all_open_oco_order' => [
                'route' => '/api/v3/opefalserderList',
                'method' => 'GET',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
            'account_info' => [
                'route' => '/api/v3/account',
                'method' => 'GET',
                'apiKey' => true,
                'params' => [
                    'signature' => true,
                    'recvWindow' => false,
                    'timestamp' => true,
                ],
            ],
        ];
    }
}